name: Angular CI/CD

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install, lint, test, build
      run: |
        npm install
        npm run lint
        npm run test
        npm run build:prod
      env:
        CI: true
        
